theme = "kyoto_night"

[editor]
line-number = "relative"
color-modes = true
mouse = false
undercurl = true
end-of-line-diagnostics = "hint"
gutters = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]

[editor.statusline]
left = ["mode", "separator", "version-control", "separator", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "file-type", "position"]
separator = " "

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = false

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
