theme = "kyoto_night"

[editor]
line-number = "relative"
mouse = false
undercurl = true
end-of-line-diagnostics = "hint"
gutters = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]

[editor.statusline]
left = ["mode", "version-control", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "file-type", "position"]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = false

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"
