version = 3
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '➜'
    foreground = '#62ED8B'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = '#56B6C2'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template  = " git:(<#DDB15F>{{ .HEAD }} {{ .BranchStatus }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }})"
    foreground = '#D4AAFC'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ""
      fetch_status  = true
      fetch_stash_count = true
      fetch_worktree_count = true
          
          
  [[blocks.segments]]
    template = ' '
    foreground = '#DCB977'
    type = 'status'
    style = 'plain'
