inherits = "ayu_dark"

"ui.background" = { fg = "cyan" }
"ui.linenr.selected" = "orange"

# [palette]
# background = "#0f1419"
# foreground = "#bfbdb6"

# black = "#131721"
# blue = "#59c2ff"
# dark_gray = "#2d3640"
# cyan = "#73b8ff"
# gray = "#5c6773"
# green = "#aad94c"
# magenta = "#d2a6ff"
# orange = "#ff8f40"
# red = "#f07178"
# yellow = "#e6b450"
